site_name: RUIHAN.ORG 
site_url: https://ruihan.org
repo_name: iurnah/ruihan.org
repo_url: https://github.com/iurnah/ruihan.org
edit_uri: ""

copyright: 'Copyright &copy; 2020 Rui Han'

theme:
  name: 'material'
  palette:
    primary: 'black'
    accent: 'black'
  feature:
    tabs: true 

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.arithmatex
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

plugins:
  - search
  - minify:
      minify_html: true

nav:
  - Books:
    - Accelerated C++: books/accelerated-cpp/notes.md
  - Course Notes:
    - CS224N Lecture Notes: courses/cs224n/lec-notes.md
    - CS224N Write-up: courses/cs224n/write-up.md
    - 6.431 Probability: courses/6.431-probability/notes.md
    - Func Prog Principles in Scala: courses/func-prog-in-scala/notes.md
  - Leetcode: 
    - Array: leetcode/array/notes.md
    - Binary Search: leetcode/binary-search/notes.md
    - Backtracking: leetcode/backtracking/notes.md
    - Union Find: leetcode/union-find/notes.md
  - Research:
    - Coalition Game: research/coalition-game/notes.md
    - Contextual Multi-Armed Bandit: research/contextual-bandit/notes.md
    - TF-IDF for Information Retrieval: research/tfidf-score/notes.md
  - SEED Labs:
    - Public Key Cryptography and PKI: seedlabs/public-key-cryptography-and-pki/notes.md

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
