site_name: RUIHAN.ORG
site_url: https://ruihan.org
repo_name: iurnah/ruihan.org
repo_url: https://github.com/iurnah/ruihan.org
edit_uri: ""

copyright: 'Copyright &copy; 2020 Rui Han'

theme:
  name: material
  palette:
    scheme: default
    primary: black
    accent: black
  features:
    - navigation.tabs

markdown_extensions:
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      linenums: false
      linenums_style: pymdownx.inline
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.arithmatex
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

plugins:
  - search
  - minify:
      minify_html: true

nav:
  - Home: index.md
  - Books:
    - Index: books/index.md
    - Accelerated C++: books/accelerated-cpp/notes.md
    - Mining Massive Datasets: books/mining-massive-datasets/notes.md
  - Courses:
    - Index: courses/index.md
    - Machine Learning (Coursera): courses/machine-learning-coursera/notes.md
    - CS224N Lecture Notes: courses/cs224n/lec-notes.md
    - CS224N Write-up: courses/cs224n/write-up.md
    - Convolutional Neural Networks: courses/coursera-dl4-cnn/notes.md
    - Mining Massive Data Sets: courses/mining-massive-datasets/notes.md
    - 6.431 Probability: courses/6.431-probability/notes.md
    - Learning From Data: courses/learning-from-data/notes.md
    - Nine Chapter Algorithms: courses/9chap-algorithms/notes.md
    - Nine Chapter System Design: courses/9chap-system-design/notes.md
    - Nine Chapter Dynamic Programming: courses/9chap-dynamic-prog/notes.md
    - Functional Programming Principles in Scala: courses/func-prog-in-scala/notes.md
    - Applied Scrum for Agile Project Management: courses/applied-scrum-for-agile/notes.md
    - Concurrent Programming in Java: courses/concurrent-prog-java/notes.md
  - Leetcode:
    - Index: leetcode/index.md
    - Favorite: leetcode/favorite/notes.md
    - Array: leetcode/array/notes.md
    - Backtracking: leetcode/backtracking/notes.md
    - Binary Search: leetcode/binary-search/notes.md
    - Binary Indexed Tree: leetcode/binary-indexed-tree/notes.md
    - Breadth-First Search (BFS): leetcode/breadth-first-search/notes.md
    - Depth-First Search (DFS): leetcode/depth-first-search/notes.md
    - Dynamic Programming: leetcode/dynamic-programming/notes.md
    - Graph: leetcode/graph/notes.md
    - Heap: leetcode/heap/notes.md
    - Interval: leetcode/interval/notes.md
    - Linked List: leetcode/linked-list/notes.md
    - Math: leetcode/math/notes.md
    - Reservoir Sampling: leetcode/reservoir-sampling/notes.md
    - Stack: leetcode/stack/notes.md
    - String: leetcode/string/notes.md
    - Tree: leetcode/tree/notes.md
    - Trie: leetcode/trie/notes.md
    - Union Find: leetcode/union-find/notes.md
  - Research:
    - Index: research/index.md
    - Paper Reading: research/paper-reading/notes.md
    - Coalition Game: research/coalition-game/notes.md
    - Contextual Multi-Armed Bandit: research/contextual-bandit/notes.md
    - TF-IDF for Information Retrieval: research/tfidf-score/notes.md
  - SEED Labs:
    - Index: seedlabs/index.md
    - Applied Cryptograph Notes: seedlabs/applied-crypto/notes.md
    - Public Key Cryptography and PKI: seedlabs/public-key-cryptography-and-pki/notes.md
  - System Design:
    - Index: system-design/index.md
    - How Browser Works: system-design/browser/notes.md
    - Concurrency and Synchronization: system-design/concurrency/notes.md
    - Distributed System Concepts: system-design/concepts/notes.md
    - Design Patterns: system-design/patterns/notes.md
    - How to Design Crawler: system-design/problems/crawler/notes.md
    - How to Design TinyUrl: system-design/problems/tinyurl/notes.md
    - How to Design Twitter: system-design/problems/twitter/notes.md
    - How to Deisgn Scheduler: system-design/problems/scheduler/notes.md
    - How to Design Ticketmaster: system-design/problems/ticketmaster/notes.md

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
